# Fix DXF PolyfaceMesh -> Polyline collapse
# Replace existing read_polyline() with read_polyline_entity() that properly detects and builds PolyfaceMesh

with open('src/io/dxf/reader/section_reader.rs', 'rb') as f:
    data = f.read()

# 1. Replace the 'read_polyline' function with a new 'read_polyline_entity' function
old_fn_start = b'    /// Read a POLYLINE entity\r\n    fn read_polyline(&mut self) -> Result<Option<Polyline>> {\r\n        use crate::entities::polyline::Vertex3D;\r\n'
old_fn_body_start_idx = data.find(old_fn_start)
print("old fn start found:", old_fn_body_start_idx >= 0)

# Find end of read_polyline function (the closing brace)
old_fn_end_marker = b'        Ok(Some(polyline))\r\n    }\r\n\r\n    /// Read an LWPOLYLINE entity'
old_fn_end_idx = data.find(old_fn_end_marker)
print("old fn end found:", old_fn_end_idx >= 0)

old_fn = data[old_fn_body_start_idx : old_fn_end_idx + len(old_fn_end_marker)]
print("old fn length:", len(old_fn))

new_fn = (
    b'    /// Read a POLYLINE or POLYFACE MESH entity, returning the appropriate EntityType.\r\n'
    b'    fn read_polyline_entity(&mut self) -> Result<Option<EntityType>> {\r\n'
    b'        use crate::entities::polyline::Vertex3D;\r\n'
    b'        use crate::entities::polyface_mesh::{\r\n'
    b'            PolyfaceMesh, PolyfaceVertex, PolyfaceFace,\r\n'
    b'            PolyfaceMeshFlags, PolyfaceVertexFlags,\r\n'
    b'        };\r\n'
    b'\r\n'
    b'        let mut common = EntityCommon::new();\r\n'
    b'        let mut flags: i16 = 0;\r\n'
    b'        let mut elevation = 0.0f64;\r\n'
    b'        let mut vertex_count: i16 = 0;\r\n'
    b'        let mut face_count: i16 = 0;\r\n'
    b'        // Polyline plain fields\r\n'
    b'        let mut polyline_vertices: Vec<Vertex3D> = Vec::new();\r\n'
    b'        // Polyface fields\r\n'
    b'        let mut pface_vertices: Vec<PolyfaceVertex> = Vec::new();\r\n'
    b'        let mut pface_faces: Vec<PolyfaceFace> = Vec::new();\r\n'
    b'\r\n'
    b'        while let Some(pair) = self.reader.read_pair()? {\r\n'
    b'            if pair.code == 0 {\r\n'
    b'                if pair.value_string == "VERTEX" {\r\n'
    b'                    // --- Read one VERTEX subentity ---\r\n'
    b'                    let mut vx = 0.0f64;\r\n'
    b'                    let mut vy = 0.0f64;\r\n'
    b'                    let mut vz = 0.0f64;\r\n'
    b'                    let mut vflags: i16 = 0;\r\n'
    b'                    let mut vi1: i16 = 0;\r\n'
    b'                    let mut vi2: i16 = 0;\r\n'
    b'                    let mut vi3: i16 = 0;\r\n'
    b'                    let mut vi4: i16 = 0;\r\n'
    b'                    while let Some(vpair) = self.reader.read_pair()? {\r\n'
    b'                        if vpair.code == 0 {\r\n'
    b'                            self.reader.push_back(vpair);\r\n'
    b'                            break;\r\n'
    b'                        }\r\n'
    b'                        match vpair.code {\r\n'
    b'                            10 => { if let Some(v) = vpair.as_double() { vx = v; } }\r\n'
    b'                            20 => { if let Some(v) = vpair.as_double() { vy = v; } }\r\n'
    b'                            30 => { if let Some(v) = vpair.as_double() { vz = v; } }\r\n'
    b'                            70 => { if let Some(v) = vpair.as_i16() { vflags = v; } }\r\n'
    b'                            71 => { if let Some(v) = vpair.as_i16() { vi1 = v; } }\r\n'
    b'                            72 => { if let Some(v) = vpair.as_i16() { vi2 = v; } }\r\n'
    b'                            73 => { if let Some(v) = vpair.as_i16() { vi3 = v; } }\r\n'
    b'                            74 => { if let Some(v) = vpair.as_i16() { vi4 = v; } }\r\n'
    b'                            _ => {}\r\n'
    b'                        }\r\n'
    b'                    }\r\n'
    b'                    // PolyfaceVertexFlags::POLYFACE_MESH = 128 => face record\r\n'
    b'                    // PolyfaceVertexFlags::POLYGON_MESH  = 64  => geometry vertex\r\n'
    b'                    if (vflags & 128) != 0 {\r\n'
    b'                        // Face record\r\n'
    b'                        let mut face = PolyfaceFace {\r\n'
    b'                            common: EntityCommon::default(),\r\n'
    b'                            flags: PolyfaceVertexFlags::NONE,\r\n'
    b'                            index1: vi1,\r\n'
    b'                            index2: vi2,\r\n'
    b'                            index3: vi3,\r\n'
    b'                            index4: vi4,\r\n'
    b'                            color: None,\r\n'
    b'                        };\r\n'
    b'                        face.flags = PolyfaceVertexFlags::from_bits_truncate(vflags);\r\n'
    b'                        pface_faces.push(face);\r\n'
    b'                    } else if (vflags & 64) != 0 {\r\n'
    b'                        // Geometry vertex\r\n'
    b'                        let mut v = PolyfaceVertex {\r\n'
    b'                            common: EntityCommon::default(),\r\n'
    b'                            location: crate::types::Vector3::new(vx, vy, vz),\r\n'
    b'                            flags: PolyfaceVertexFlags::from_bits_truncate(vflags),\r\n'
    b'                            bulge: 0.0,\r\n'
    b'                            start_width: 0.0,\r\n'
    b'                            end_width: 0.0,\r\n'
    b'                            curve_tangent: 0.0,\r\n'
    b'                            id: 0,\r\n'
    b'                        };\r\n'
    b'                        let _ = v;\r\n'
    b'                        pface_vertices.push(PolyfaceVertex {\r\n'
    b'                            common: EntityCommon::default(),\r\n'
    b'                            location: crate::types::Vector3::new(vx, vy, vz),\r\n'
    b'                            flags: PolyfaceVertexFlags::from_bits_truncate(vflags),\r\n'
    b'                            bulge: 0.0,\r\n'
    b'                            start_width: 0.0,\r\n'
    b'                            end_width: 0.0,\r\n'
    b'                            curve_tangent: 0.0,\r\n'
    b'                            id: 0,\r\n'
    b'                        });\r\n'
    b'                    } else {\r\n'
    b'                        polyline_vertices.push(Vertex3D::new(\r\n'
    b'                            crate::types::Vector3::new(vx, vy, vz),\r\n'
    b'                        ));\r\n'
    b'                    }\r\n'
    b'                } else if pair.value_string == "SEQEND" {\r\n'
    b'                    while let Some(seqend_pair) = self.reader.read_pair()? {\r\n'
    b'                        if seqend_pair.code == 0 {\r\n'
    b'                            self.reader.push_back(seqend_pair);\r\n'
    b'                            break;\r\n'
    b'                        }\r\n'
    b'                    }\r\n'
    b'                    break;\r\n'
    b'                } else {\r\n'
    b'                    self.reader.push_back(pair);\r\n'
    b'                    break;\r\n'
    b'                }\r\n'
    b'            } else {\r\n'
    b'                match pair.code {\r\n'
    b'                    8 => common.layer = pair.value_string.clone(),\r\n'
    b'                    62 => {\r\n'
    b'                        if let Some(ci) = pair.as_i16() {\r\n'
    b'                            common.color = Color::from_index(ci);\r\n'
    b'                        }\r\n'
    b'                    }\r\n'
    b'                    370 => {\r\n'
    b'                        if let Some(lw) = pair.as_i16() {\r\n'
    b'                            common.line_weight = LineWeight::from_value(lw);\r\n'
    b'                        }\r\n'
    b'                    }\r\n'
    b'                    70 => {\r\n'
    b'                        if let Some(f) = pair.as_i16() {\r\n'
    b'                            flags = f;\r\n'
    b'                        }\r\n'
    b'                    }\r\n'
    b'                    30 => {\r\n'
    b'                        if let Some(z) = pair.as_double() {\r\n'
    b'                            elevation = z;\r\n'
    b'                        }\r\n'
    b'                    }\r\n'
    b'                    71 => {\r\n'
    b'                        if let Some(vc) = pair.as_i16() {\r\n'
    b'                            vertex_count = vc;\r\n'
    b'                        }\r\n'
    b'                    }\r\n'
    b'                    72 => {\r\n'
    b'                        if let Some(fc) = pair.as_i16() {\r\n'
    b'                            face_count = fc;\r\n'
    b'                        }\r\n'
    b'                    }\r\n'
    b'                    _ => { self.try_read_common_entity_code(&pair, &mut common)?; }\r\n'
    b'                }\r\n'
    b'            }\r\n'
    b'        }\r\n'
    b'\r\n'
    b'        // PolyfaceMeshFlags::POLYFACE_MESH = 64 (bit 6)\r\n'
    b'        let is_polyface = (flags & 64) != 0;\r\n'
    b'\r\n'
    b'        if is_polyface || !pface_vertices.is_empty() || !pface_faces.is_empty() {\r\n'
    b'            let mut mesh = PolyfaceMesh::new();\r\n'
    b'            mesh.common = common;\r\n'
    b'            mesh.flags = PolyfaceMeshFlags::from_bits_truncate(flags);\r\n'
    b'            mesh.elevation = elevation;\r\n'
    b'            mesh.vertices = pface_vertices;\r\n'
    b'            mesh.faces = pface_faces;\r\n'
    b'            Ok(Some(EntityType::PolyfaceMesh(mesh)))\r\n'
    b'        } else {\r\n'
    b'            let mut polyline = Polyline::new();\r\n'
    b'            polyline.common = common;\r\n'
    b'            if (flags & 1) != 0 {\r\n'
    b'                polyline.close();\r\n'
    b'            }\r\n'
    b'            polyline.vertices = polyline_vertices;\r\n'
    b'            Ok(Some(EntityType::Polyline(polyline)))\r\n'
    b'        }\r\n'
    b'    }\r\n'
    b'\r\n'
    b'    /// Read an LWPOLYLINE entity'
)

data = data.replace(old_fn, new_fn, 1)
print("fn replaced:", new_fn in data)

# 2. Update both call sites: replace read_polyline()? + EntityType::Polyline wrap
# Call site format in blocks:
old_cs1 = (
    b'                    "POLYLINE" => {\r\n'
    b'                        if let Some(entity) = self.read_polyline()? {\r\n'
    b'                            block_entities.push(EntityType::Polyline(entity));\r\n'
    b'                        }\r\n'
    b'                    }'
)
new_cs1 = (
    b'                    "POLYLINE" => {\r\n'
    b'                        if let Some(entity) = self.read_polyline_entity()? {\r\n'
    b'                            block_entities.push(entity);\r\n'
    b'                        }\r\n'
    b'                    }'
)
print("block callsite found:", old_cs1 in data)
data = data.replace(old_cs1, new_cs1, 1)

# Call site format in entities:
old_cs2 = (
    b'                    "POLYLINE" => {\r\n'
    b'                        if let Some(entity) = self.read_polyline()? {\r\n'
    b'                            let _ = document.add_entity(EntityType::Polyline(entity));\r\n'
    b'                        }\r\n'
    b'                    }'
)
new_cs2 = (
    b'                    "POLYLINE" => {\r\n'
    b'                        if let Some(entity) = self.read_polyline_entity()? {\r\n'
    b'                            let _ = document.add_entity(entity);\r\n'
    b'                        }\r\n'
    b'                    }'
)
print("entity callsite found:", old_cs2 in data)
data = data.replace(old_cs2, new_cs2, 1)

with open('src/io/dxf/reader/section_reader.rs', 'wb') as f:
    f.write(data)
print('done')
